GROQ_API_KEY= "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"
REPLICATE_API_TOKEN= "r8_0ev6L2gx0KCVPI6D9r3TeYQ4DsMy4VW3fZ1Ug"
GEMINI_API_KEY="AIzaSyBWhuNDd7Evloy9mNKRB65NWrEK63kowBg" # Google AI Studio
HG_API_KEY= "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" # Hugging Face